export const StudentsData = [
  {
    id: 1,
    name: "Sanginov Otabek Muratovich",
    typeStudent: "Magistr",
    placeStudy: "Toshkent davlat texnika universiteti",
    separatedPrice: 2000000,
    contractAmount: 25000000,
  },
  {
    id: 2,
    name: "Ismoilov Shohruz",
    typeStudent: "Bakalavr",
    placeStudy: "Qoraqalpog'iston davlat universiteti",
    separatedPrice: 1800000,
    contractAmount: 22000000,
  },
  {
    id: 3,
    name: "Ismailova Malika",
    typeStudent: "Magistr",
    placeStudy: "Namangan davlat universiteti",
    separatedPrice: 2100000,
    contractAmount: 26000000,
  },
  {
    id: 4,
    name: "Nurullaev Shukhrat",
    typeStudent: "Bakalavr",
    placeStudy: "Samarqand davlat universiteti",
    separatedPrice: 1900000,
    contractAmount: 23000000,
  },
  {
    id: 5,
    name: "Omonov Munisa",
    typeStudent: "Magistr",
    placeStudy: "Farg'ona davlat universiteti",
    separatedPrice: 2200000,
    contractAmount: 27000000,
  },
  {
    id: 6,
    name: "Abdullayev Bobur",
    typeStudent: "Bakalavr",
    placeStudy: "Jizzax davlat pedagogika instituti",
    separatedPrice: 1950000,
    contractAmount: 24000000,
  },
  {
    id: 7,
    name: "Qodirova Feruza",
    typeStudent: "Magistr",
    placeStudy: "Toshkent axborot texnologiyalari universiteti",
    separatedPrice: 2150000,
    contractAmount: 26500000,
  },
  {
    id: 8,
    name: "Rahmonov Jamshid",
    typeStudent: "Bakalavr",
    placeStudy: "Navoiy davlat san'at va madaniyat instituti",
    separatedPrice: 1850000,
    contractAmount: 22500000,
  },
  {
    id: 9,
    name: "Tursunov Azizbek",
    typeStudent: "Magistr",
    placeStudy: "Qarshi davlat universiteti",
    separatedPrice: 2050000,
    contractAmount: 25500000,
  },
  {
    id: 10,
    name: "Zokirova Nigora",
    typeStudent: "Bakalavr",
    placeStudy: "Buxoro davlat universiteti",
    separatedPrice: 1750000,
    contractAmount: 21500000,
  },
  {
    id: 11,
    name: "Ahmedov Shahzod",
    typeStudent: "Magistr",
    placeStudy: "Xorazm davlat universiteti",
    separatedPrice: 1950000,
    contractAmount: 23500000,
  },
  {
    id: 12,
    name: "Juraev Sanjar",
    typeStudent: "Bakalavr",
    placeStudy: "Surxondaryo davlat universiteti",
    separatedPrice: 1800000,
    contractAmount: 22000000,
  },
  {
    id: 13,
    name: "Usmonov Shohjahon",
    typeStudent: "Magistr",
    placeStudy: "Sirdaryo davlat universiteti",
    separatedPrice: 2100000,
    contractAmount: 26000000,
  },
  {
    id: 14,
    name: "Saidov Nodir",
    typeStudent: "Bakalavr",
    placeStudy: "Qashqadaryo davlat universiteti",
    separatedPrice: 1900000,
    contractAmount: 23000000,
  },
  {
    id: 15,
    name: "Oripov Elmurod",
    typeStudent: "Magistr",
    placeStudy: "Andijon davlat texnika universiteti",
    separatedPrice: 2200000,
    contractAmount: 27000000,
  },
  {
    id: 16,
    name: "Ismoilova Fotima",
    typeStudent: "Bakalavr",
    placeStudy: "Farg'ona axborot texnologiyalari universiteti",
    separatedPrice: 1950000,
    contractAmount: 24000000,
  },
  {
    id: 17,
    name: "Ochilov Abdukarim",
    typeStudent: "Magistr",
    placeStudy: "Namangan axborot texnologiyalari universiteti",
    separatedPrice: 2150000,
    contractAmount: 26500000,
  },
  {
    id: 18,
    name: "Olimov Alisher",
    typeStudent: "Bakalavr",
    placeStudy: "Jizzax davlat san'at va madaniyat instituti",
    separatedPrice: 1850000,
    contractAmount: 22500000,
  },
  {
    id: 19,
    name: "Qosimov Farrux",
    typeStudent: "Magistr",
    placeStudy: "Toshkent axborot texnologiyalari universiteti",
    separatedPrice: 2050000,
    contractAmount: 25500000,
  },
  {
    id: 20,
    name: "Xamidov Farruh",
    typeStudent: "Bakalavr",
    placeStudy: "Navoiy davlat san'at va madaniyat instituti",
    separatedPrice: 1750000,
    contractAmount: 21500000,
  },
  {
    id: 21,
    name: "Soliev Nurbek",
    typeStudent: "Magistr",
    placeStudy: "Qarshi davlat universiteti",
    separatedPrice: 1950000,
    contractAmount: 23500000,
  },
  {
    id: 22,
    name: "Shukhratov Shohruh",
    typeStudent: "Bakalavr",
    placeStudy: "Buxoro davlat universiteti",
    separatedPrice: 1800000,
    contractAmount: 22000000,
  },
  {
    id: 23,
    name: "Toshev Sanjar",
    typeStudent: "Magistr",
    placeStudy: "Xorazm davlat universiteti",
    separatedPrice: 2100000,
    contractAmount: 26000000,
  },
  {
    id: 24,
    name: "Shamsiyev Azizbek",
    typeStudent: "Bakalavr",
    placeStudy: "Surxondaryo davlat universiteti",
    separatedPrice: 1900000,
    contractAmount: 23000000,
  },
  {
    id: 25,
    name: "Sattorov Samandar",
    typeStudent: "Magistr",
    placeStudy: "Sirdaryo davlat universiteti",
    separatedPrice: 2200000,
    contractAmount: 27000000,
  },
  {
    id: 26,
    name: "Rahmonov Ulugbek",
    typeStudent: "Bakalavr",
    placeStudy: "Qashqadaryo davlat universiteti",
    separatedPrice: 1950000,
    contractAmount: 24000000,
  },
  {
    id: 27,
    name: "Rustamov Rustam",
    typeStudent: "Magistr",
    placeStudy: "Andijon davlat texnika universiteti",
    separatedPrice: 2150000,
    contractAmount: 26500000,
  },
  {
    id: 28,
    name: "Ravshanov Ravshan",
    typeStudent: "Bakalavr",
    placeStudy: "Farg'ona axborot texnologiyalari universiteti",
    separatedPrice: 1850000,
    contractAmount: 22500000,
  },
  {
    id: 29,
    name: "Qobilov Qobil",
    typeStudent: "Magistr",
    placeStudy: "Namangan axborot texnologiyalari universiteti",
    separatedPrice: 2050000,
    contractAmount: 25500000,
  },
  {
    id: 30,
    name: "Xusanov Doston",
    typeStudent: "Magistr",
    placeStudy: "Andijon davlat texnika universiteti",
    separatedPrice: 2100000,
    contractAmount: 26000000,
  },
];
